spring:
  profiles:
    active: revo
---
server:
  port: 8182
  contextPath: /Demo
---
spring:
  profiles: revo
  cache:
    ehcache:
      config: classpath:ehcache.xml
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jmx:
    default-domain: Demo
datasource:
  demo:
    url: jdbc:oracle:thin:@192.168.1.248:1521/orcl
    username: DEMO
    password: DEMO
    driverClassName: oracle.jdbc.OracleDriver
    defaultSchema: DEMO
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: none
      show_sql: true
      format_sql: none
      dialect: org.hibernate.dialect.Oracle10gDialect